spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:mem:board;MODE=MySQL
    url: jdbc:h2:tcp://localhost/~/borad;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              org.hibernate.type.descriptor.sql.BasicBinder: trace
    springframework:
      web.servlet: debug